name: deploy-appengine Unit

on: [push, pull_request]

jobs:
  run:
    name: deploy-appengine-go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1